insert into Color values (1,'Black');
insert into Color values (2,'Night');
insert into Color values (3,'Gunmetal');
insert into Color values (4,'Red');
insert into Color values (5,'Platinum');
insert into Color values (6,'Metalic Silver');
insert into Color values (7,'Midnight Blue');
insert into Color values (8,'Forest Green');
insert into Color values (9,'Milk White');
insert into Color values (10,'White');